# Site
name: 'Anti Bet Collective'
description: 'Combatendo as casas de apostas esportivas online e seus impactos negativos na sociedade.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'antibetcollective'
email: 'antibetcollective@outlook.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
locale: pt-BR

include: ['_pages']
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  antibetcollective:
    name: antibetcollective
    site: https://antibetcollective.github.io
    avatar: /assets/images/avatar1.jpg
    bio: "Oi, nós somos o Anti Bet Collective. Esperamos poder passar informações úteis e incentivar mais ações conscientes."
    email: antibetcollective@outlook.com
    instagram: https://instagram.com/antibetcollective


# Defaults
defaults:
  # all posts
  - scope:
      path: '_posts'
    values:
      layout: post
      author: antibetcollective
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: '_pages'
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
    vendor,
  ]
